### PR TITLE
Changed text enum to class via protocol for ease of replacement

### PR DESCRIPTION
**Pull request by ehlersd**

### CODE REVIEW

**Comment by KeiroMidori** [comment]
I second this PR. Any plans on merging this ?

**Comment by ivanvorobei** [comment]
I not sure about changes to class it, I have plans full redo `SPPermissions` soon

**Comment by KeiroMidori** [comment]
Roger that ! Good luck on this

**Comment by ivanvorobei** [comment]
Closed because released `6.0` version.

**Pull request closed without merging**
