### PR TITLE
Precise location support for iOS 14.0+

### PR DESCRIPTION
**Pull request by Strobocop**
Fix for [this issue.](https://github.com/ivanvorobei/SPPermissions/issues/205)

Adds support for explicitly requiring precise location in iOS 14.0+.

### CODE REVIEW

**Comment by ivanvorobei** [comment]
Wow, thanks for your work! 
I think all good, I can confirm it later today and release also today.

**Comment by ivanvorobei** [comment]
I checked code, I have some propose for clean it.

1) Change names
From `SPPreciseLocationWhenInUsePermission` to `SPLocationWhenInUsePrecisePermission` example. Also for build flags and other places where it using.

2) Request code is same, so better use inheritance and ovveride state only, example:

```swift
class SPLocationWhenInUsePrecisePermission: SPLocationWhenInUsePermission {
    
    override var status: SPPermissions.PermissionStatus {
        // new logic here
    }
}
```

If you are ready do it, let me know. If you can't - I can do it in time. Waiting feedback from you.

**Comment by Strobocop** [comment]
Thanks for the feedback @ivanvorobei.

Ideally I would parameterize the permission enum with an associated value to allow for precision, but that seemed like a larger refactor so I went the path of least resistance. I think your proposed solution minimizes refactor while keeping the code clean. Will update shortly.

**Comment by ivanvorobei** [comment]
@Strobocop yes, you are right. Thanks and waiting it!

**Comment by ivanvorobei** [comment]
Thanks, preparing to release `6.8.4` version.

**Pull request merged**
