### PR TITLE
tvOS support

### PR DESCRIPTION
**Pull request by RomanPodymov**
Hello.
Thank you for SPPermissions.
In this pull request I added support for tvOS. Some permissions are not supported for tvOS, that's why I made them available for iOS only with `#if os(iOS)`. Tested it with CocoaPods.
Fixed `SPPermissions.dialog` example in README.

### CODE REVIEW

**Comment by ivanvorobei** [comment]
Wow! Thanks for your work!

I have not encountered development for TV, I hope you can help. Could you add a new target - example for tv in project?

**Comment by RomanPodymov** [comment]
> Wow! Thanks for your work!
> 
> I have not encountered development for TV, I hope you can help. Could you add a new target - example for tv in project?

Done. However I see some bugs in the example for tvOS. Would you please create a branch for tvOS support?

**Comment by ivanvorobei** [comment]
I see example for tv, but target empty - no any swift file. 

Why need new branch? Why you can't add to this branch? I don’t find fault, I just don’t understand what you want to do.

**Comment by ivanvorobei** [comment]
I think need remove for Apple TV `List` & `Dialog` controllers. Also I am try call with `Native` any permission - it not work (maybe need request permission only on real device?)

**Comment by RomanPodymov** [comment]
Hello @ivanvorobei 
OK, I will fix all tvOS-related issues in the master branch.
Permissions are also supported by tvOS simulator, I will check why `Native` is not displaying in the tvOS example.

**Comment by RomanPodymov** [comment]
@ivanvorobei Left `SPPermissionsDialogController` and `SPPermissionsListController` for iOS only. Fixed the issue with tvOS example.

**Comment by ivanvorobei** [comment]
@RomanPodymov for me in tv simulator permission not requested. Maybe I do some this wrong? Simple run and tap `play` for request permission.

**Comment by RomanPodymov** [comment]
@ivanvorobei Fixed, check it please.

**Comment by ivanvorobei** [comment]
For now all ok! Thanks) 
Let me 1-3 hours for check all changes and after it I am merge and publish new version for CocoaPods.

**Comment by ivanvorobei** [comment]
I am publish new version `5.1`. @RomanPodymov many thanks for your work and time! 

If anybody can help, I am add new item in [Cooperation](https://github.com/ivanvorobei/SPPermissions#сooperation) section about icon for example target.

**Pull request merged**
