### PR TITLE
Add a permission request hook to allow permission request pre-processing

### PR DESCRIPTION
**Pull request by nivanchikov**
This pull request adds a new `SPPermissionsDelegate` method which is called before the framework starts processing the permission request. 
This gives the API consumers a chance to manually attempt to request necessary permissions, e.g try to start a Bluetooth scan to force the system to display the permissions dialog. If the developer doesn't want to do any request pre-processing, they could just call the `completion` closure

Example:
```swift
func willAccess(permission: SPPermission, completion: @escaping () -> Void) {
   switch permission {
     case .bluetooth:
         BluetoothManager.requestBluetoothPermissions(completion)
    default:
        completion()
    }
}
```

### CODE REVIEW

**Comment by ivanvorobei** [comment]
Good day! Thanks for your work! 
You can describe when need this case?

**Comment by nivanchikov** [comment]
sure, we use SPPermissions in one of our projects and specifically needed the Bluetooth permission. 

Since the actual permissions request wasn't available in the latest release (5.2.6) (see #134) we implemented this callback to trigger the Bluetooth scan on our end, which brings up the system permissions dialog. After that, the framework successfully validates the permission on its end.

**Comment by ivanvorobei** [comment]
Maybe better add Bluetooth request to source code? For now it no implement, because I don't know how correct it request.

**Comment by nivanchikov** [comment]
I'm not sure it's quite correct to add the Bluetooth permissions to the framework itself, cause it involves creating a CBCentralManager object, starting the scan and waiting for the power state callback. We haven't found another way to trigger the permissions alert.

Would you really want to include such setup into the framework itself?

**Comment by ivanvorobei** [comment]
Need implement only request permission, you can do it?

**Comment by nivanchikov** [comment]
Again - the system won't show the permission dialog unless the app creates a CBCentralManager (and perhaps starts the scan). This can be implemented similar to `SPRequestPermissionLocationHandler` or the same feature can be provided as a pre-permission hook in the current solution. 

If you want to encapsulate the permissions request handling inside the framework, we can try creating something similar to `SPRequestPermissionLocationHandler`.

**Comment by ivanvorobei** [comment]
Yes, I mean it. You can, please?

**Comment by ivanvorobei** [comment]
@nivanchikov any news?

**Comment by bielikb** [comment]
There are several ways how to invoke the bluetooth permissions, as @nivanchikov correctly pointed out, it's tied to creation of an instance of central, peripheral or any other manager that accesses the bluetooth services on device.

One of the possible code sample looks like this:
```
CBPeripheralManager(
            delegate: self,
            queue: nil,
            options: [ CBPeripheralManagerOptionShowPowerAlertKey: true ]
        )
```

it'd be clever to give a user of the `SPPermissions` API  a way to provide the implementation that should be executed, e.g. when authorising bluetooth permissions. 
This way, `SPPermissions` library would be flexible and wouldn't be tied to one specific solution.

**Pull request closed without merging**
