### PR TITLE
Fix example to use 'SPPermission' as framework

### PR DESCRIPTION
**Pull request by cozzin**
Before fix this issue https://github.com/ivanvorobei/SPPermission/pull/128#issuecomment-528598025, I think we should fix example to use 'SPPermission' as framework.

### CODE REVIEW

**Comment by ivanvorobei** [comment]
@cozzin need update only `source` folder, add your functions. Example no need change

**Comment by cozzin** [comment]
@ivanvorobei Okay, I will add function to `source` folder in other PR.
However, I think the example should use the same SPPermission source.
For now, you need to manually sync the sources in the framework and the example files.

**Comment by ivanvorobei** [comment]
@cozzin for now how you add `SPPermission` to example project? via cocoapds? 
Many changes in PR, not understand...

**Comment by ivanvorobei** [comment]
In new version I am add target with example project.

**Pull request closed without merging**
